# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1100)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("font-color: rgb(255, 255, 255);\n"
"background-color: rgb(28, 30, 35);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-2, 0, 291, 1200))
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(0, 6, 34);\n"
"border-top-color: rgb(170, 85, 127);")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.switch_progress = QtWidgets.QPushButton(self.groupBox)
        self.switch_progress.setGeometry(QtCore.QRect(-1, 360, 291, 70))
        self.switch_progress.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_progress.setAutoFillBackground(False)
        self.switch_progress.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Дизайн/icons/Прогресс.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.switch_progress.setIcon(icon)
        self.switch_progress.setIconSize(QtCore.QSize(290, 70))
        self.switch_progress.setObjectName("switch_progress")
        self.switch_buy = QtWidgets.QPushButton(self.groupBox)
        self.switch_buy.setGeometry(QtCore.QRect(-1, 180, 291, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_buy.sizePolicy().hasHeightForWidth())
        self.switch_buy.setSizePolicy(sizePolicy)
        self.switch_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_buy.setAcceptDrops(False)
        self.switch_buy.setAutoFillBackground(False)
        self.switch_buy.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Дизайн/icons/Покупки.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.switch_buy.setIcon(icon1)
        self.switch_buy.setIconSize(QtCore.QSize(290, 70))
        self.switch_buy.setObjectName("switch_buy")
        self.switch_to_do = QtWidgets.QPushButton(self.groupBox)
        self.switch_to_do.setGeometry(QtCore.QRect(-1, 90, 290, 70))
        self.switch_to_do.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_to_do.setText("")
        icon = QtGui.QIcon.fromTheme("C:\\Users\\Общий\\Desktop\\del.png")
        self.switch_to_do.setIcon(icon)
        self.switch_to_do.setIconSize(QtCore.QSize(290, 200))
        self.switch_to_do.setObjectName("switch_to_do")
        self.switch_notes = QtWidgets.QPushButton(self.groupBox)
        self.switch_notes.setGeometry(QtCore.QRect(-1, 270, 291, 70))
        self.switch_notes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_notes.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Дизайн/icons/Заметки неактивные.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.switch_notes.setIcon(icon2)
        self.switch_notes.setIconSize(QtCore.QSize(290, 70))
        self.switch_notes.setObjectName("switch_notes")
        self.switch_all_tasks = QtWidgets.QPushButton(self.groupBox)
        self.switch_all_tasks.setGeometry(QtCore.QRect(-1, 460, 291, 70))
        self.switch_all_tasks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_all_tasks.setAutoFillBackground(False)
        self.switch_all_tasks.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Дизайн/icons/Все дела неактивное.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.switch_all_tasks.setIcon(icon3)
        self.switch_all_tasks.setIconSize(QtCore.QSize(290, 70))
        self.switch_all_tasks.setObjectName("switch_all_tasks")
        self.switch_all_buys = QtWidgets.QPushButton(self.groupBox)
        self.switch_all_buys.setGeometry(QtCore.QRect(-1, 550, 291, 70))
        self.switch_all_buys.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_all_buys.setAutoFillBackground(False)
        self.switch_all_buys.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Дизайн/icons/все покупки неактивные.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.switch_all_buys.setIcon(icon4)
        self.switch_all_buys.setIconSize(QtCore.QSize(290, 70))
        self.switch_all_buys.setObjectName("switch_all_buys")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(276, 0, 0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(28, 30, 35);\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.inp_todo = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_todo.setGeometry(QtCore.QRect(33, 51, 1210, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.inp_todo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(True)
        self.inp_todo.setFont(font)
        self.inp_todo.setAutoFillBackground(False)
        self.inp_todo.setStyleSheet("background-color: rgb(75, 77, 83);\n"
"border-color: rgb(255, 170, 255);\n"
"")
        self.inp_todo.setObjectName("inp_todo")
        self.add_todo = QtWidgets.QPushButton(self.groupBox_2)
        self.add_todo.setGeometry(QtCore.QRect(1490, 50, 61, 61))
        self.add_todo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_todo.setToolTip("")
        self.add_todo.setToolTipDuration(0)
        self.add_todo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Дизайн/icons/плюс.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_todo.setIcon(icon5)
        self.add_todo.setIconSize(QtCore.QSize(61, 61))
        self.add_todo.setCheckable(False)
        self.add_todo.setChecked(False)
        self.add_todo.setDefault(False)
        self.add_todo.setObjectName("add_todo")
        self.inp_time_todo = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_time_todo.setGeometry(QtCore.QRect(1290, 60, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.inp_time_todo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.inp_time_todo.setFont(font)
        self.inp_time_todo.setStyleSheet("background-color: rgb(75, 77, 83);")
        self.inp_time_todo.setObjectName("inp_time_todo")
        self.todo = QtWidgets.QPushButton(self.groupBox_2)
        self.todo.setGeometry(QtCore.QRect(1562, 300, 40, 40))
        self.todo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.todo.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Дизайн/icons/Выполненное дело.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.todo.setIcon(icon6)
        self.todo.setIconSize(QtCore.QSize(40, 40))
        self.todo.setObjectName("todo")
        self.text_todo = QtWidgets.QLabel(self.groupBox_2)
        self.text_todo.setGeometry(QtCore.QRect(72, 290, 1323, 45))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.text_todo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_todo.setFont(font)
        self.text_todo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_todo.setStyleSheet("border-bottom-color: rgb(0, 255, 0);")
        self.text_todo.setObjectName("text_todo")
        self.time_todo = QtWidgets.QLabel(self.groupBox_2)
        self.time_todo.setGeometry(QtCore.QRect(1440, 290, 77, 33))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.time_todo.setFont(font)
        self.time_todo.setObjectName("time_todo")
        self.not_todo = QtWidgets.QPushButton(self.groupBox_2)
        self.not_todo.setGeometry(QtCore.QRect(960, 470, 40, 40))
        self.not_todo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.not_todo.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Дизайн/icons/Не выполненное дело.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.not_todo.setIcon(icon7)
        self.not_todo.setIconSize(QtCore.QSize(40, 40))
        self.not_todo.setObjectName("not_todo")
        self.delete_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_2.setGeometry(QtCore.QRect(30, 290, 31, 38))
        self.delete_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Дизайн/icons/Удалить.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.delete_2.setIcon(icon8)
        self.delete_2.setIconSize(QtCore.QSize(31, 38))
        self.delete_2.setObjectName("delete_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, -10, 1671, 1071))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(28, 30, 35);\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.product_inp = QtWidgets.QLineEdit(self.groupBox_3)
        self.product_inp.setGeometry(QtCore.QRect(30, 61, 1071, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.product_inp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.product_inp.setFont(font)
        self.product_inp.setStyleSheet("background-color: rgb(75, 77, 83);")
        self.product_inp.setObjectName("product_inp")
        self.price_inp = QtWidgets.QLineEdit(self.groupBox_3)
        self.price_inp.setGeometry(QtCore.QRect(1130, 65, 187, 52))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.price_inp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.price_inp.setFont(font)
        self.price_inp.setStyleSheet("background-color: rgb(75, 77, 83);\n"
"")
        self.price_inp.setObjectName("price_inp")
        self.add_buy = QtWidgets.QPushButton(self.groupBox_3)
        self.add_buy.setGeometry(QtCore.QRect(1530, 60, 61, 61))
        self.add_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_buy.setToolTip("")
        self.add_buy.setToolTipDuration(0)
        self.add_buy.setText("")
        self.add_buy.setIcon(icon5)
        self.add_buy.setIconSize(QtCore.QSize(61, 61))
        self.add_buy.setCheckable(False)
        self.add_buy.setChecked(False)
        self.add_buy.setDefault(False)
        self.add_buy.setObjectName("add_buy")
        self.text_buy = QtWidgets.QLabel(self.groupBox_3)
        self.text_buy.setGeometry(QtCore.QRect(74, 286, 1323, 45))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.text_buy.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_buy.setFont(font)
        self.text_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_buy.setStyleSheet("border-bottom-color: rgb(0, 255, 0);")
        self.text_buy.setObjectName("text_buy")
        self.buy = QtWidgets.QPushButton(self.groupBox_3)
        self.buy.setGeometry(QtCore.QRect(1560, 300, 40, 40))
        self.buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buy.setText("")
        self.buy.setIcon(icon6)
        self.buy.setIconSize(QtCore.QSize(40, 40))
        self.buy.setObjectName("buy")
        self.price_text = QtWidgets.QLabel(self.groupBox_3)
        self.price_text.setGeometry(QtCore.QRect(1400, 290, 141, 33))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.price_text.setFont(font)
        self.price_text.setObjectName("price_text")
        self.not_buy = QtWidgets.QPushButton(self.groupBox_3)
        self.not_buy.setGeometry(QtCore.QRect(1440, 420, 40, 40))
        self.not_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.not_buy.setText("")
        self.not_buy.setIcon(icon7)
        self.not_buy.setIconSize(QtCore.QSize(40, 40))
        self.not_buy.setObjectName("not_buy")
        self.delete_buy = QtWidgets.QPushButton(self.groupBox_3)
        self.delete_buy.setGeometry(QtCore.QRect(40, 350, 31, 38))
        self.delete_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_buy.setText("")
        self.delete_buy.setIcon(icon8)
        self.delete_buy.setIconSize(QtCore.QSize(31, 38))
        self.delete_buy.setObjectName("delete_buy")
        self.count_inp = QtWidgets.QSpinBox(self.groupBox_3)
        self.count_inp.setGeometry(QtCore.QRect(1350, 70, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.count_inp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.count_inp.setFont(font)
        self.count_inp.setMinimum(1)
        self.count_inp.setMaximum(10000)
        self.count_inp.setObjectName("count_inp")
        self.count = QtWidgets.QLabel(self.groupBox_3)
        self.count.setGeometry(QtCore.QRect(1310, 380, 51, 33))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.count.setFont(font)
        self.count.setObjectName("count")
        self.price_for_one = QtWidgets.QLabel(self.groupBox_3)
        self.price_for_one.setGeometry(QtCore.QRect(1170, 320, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.price_for_one.setFont(font)
        self.price_for_one.setObjectName("price_for_one")
        self.already_buy = QtWidgets.QLabel(self.groupBox_3)
        self.already_buy.setGeometry(QtCore.QRect(1139, 920, 101, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.already_buy.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.already_buy.setFont(font)
        self.already_buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.already_buy.setStyleSheet("border-bottom-color: rgb(0, 255, 0);")
        self.already_buy.setObjectName("already_buy")
        self.already_pay = QtWidgets.QLabel(self.groupBox_3)
        self.already_pay.setGeometry(QtCore.QRect(1260, 920, 151, 33))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.already_pay.setFont(font)
        self.already_pay.setObjectName("already_pay")
        self.already_pay_icon = QtWidgets.QLabel(self.groupBox_3)
        self.already_pay_icon.setGeometry(QtCore.QRect(1408, 910, 31, 16))
        self.already_pay_icon.setText("")
        self.already_pay_icon.setObjectName("already_pay_icon")
        self.itogo_3 = QtWidgets.QLabel(self.groupBox_3)
        self.itogo_3.setGeometry(QtCore.QRect(1169, 960, 71, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.itogo_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.itogo_3.setFont(font)
        self.itogo_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.itogo_3.setStyleSheet("border-bottom-color: rgb(0, 255, 0);")
        self.itogo_3.setLineWidth(10)
        self.itogo_3.setObjectName("itogo_3")
        self.itogo_price = QtWidgets.QLabel(self.groupBox_3)
        self.itogo_price.setGeometry(QtCore.QRect(1260, 960, 151, 33))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.itogo_price.setFont(font)
        self.itogo_price.setObjectName("itogo_price")
        self.itogo_icon = QtWidgets.QLabel(self.groupBox_3)
        self.itogo_icon.setGeometry(QtCore.QRect(1410, 960, 31, 16))
        self.itogo_icon.setText("")
        self.itogo_icon.setObjectName("itogo_icon")
        self.change_currency = QtWidgets.QPushButton(self.groupBox_3)
        self.change_currency.setGeometry(QtCore.QRect(920, 950, 32, 38))
        self.change_currency.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_currency.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Дизайн/icons/Рубль.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.change_currency.setIcon(icon9)
        self.change_currency.setIconSize(QtCore.QSize(26, 36))
        self.change_currency.setObjectName("change_currency")
        self.change_currency_gb = QtWidgets.QGroupBox(self.groupBox_3)
        self.change_currency_gb.setGeometry(QtCore.QRect(920, 900, 136, 50))
        self.change_currency_gb.setToolTipDuration(-1)
        self.change_currency_gb.setTitle("")
        self.change_currency_gb.setObjectName("change_currency_gb")
        self.dollar_btn = QtWidgets.QPushButton(self.change_currency_gb)
        self.dollar_btn.setGeometry(QtCore.QRect(10, 5, 24, 39))
        self.dollar_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dollar_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Дизайн/icons/Доллар.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dollar_btn.setIcon(icon10)
        self.dollar_btn.setIconSize(QtCore.QSize(24, 39))
        self.dollar_btn.setObjectName("dollar_btn")
        self.euro_btn = QtWidgets.QPushButton(self.change_currency_gb)
        self.euro_btn.setGeometry(QtCore.QRect(50, 5, 32, 38))
        self.euro_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.euro_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Дизайн/icons/Евро.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.euro_btn.setIcon(icon11)
        self.euro_btn.setIconSize(QtCore.QSize(32, 38))
        self.euro_btn.setObjectName("euro_btn")
        self.rubl_btn = QtWidgets.QPushButton(self.change_currency_gb)
        self.rubl_btn.setGeometry(QtCore.QRect(98, 5, 26, 36))
        self.rubl_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rubl_btn.setText("")
        self.rubl_btn.setIcon(icon9)
        self.rubl_btn.setIconSize(QtCore.QSize(26, 36))
        self.rubl_btn.setObjectName("rubl_btn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(280, -10, 0, 1071))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(28, 30, 35);\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_4)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1581, 1021))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsBuys = PlotWidget(self.tab)
        self.graphicsBuys.setGeometry(QtCore.QRect(100, 100, 981, 671))
        self.graphicsBuys.setObjectName("graphicsBuys")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView = PlotWidget(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(100, 100, 981, 671))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(280, -10, 0, 0))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.text_note = QtWidgets.QTextEdit(self.groupBox_5)
        self.text_note.setGeometry(QtCore.QRect(32, 50, 1385, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 77, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.text_note.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_note.setFont(font)
        self.text_note.setStyleSheet("background-color: rgb(75, 77, 83);")
        self.text_note.setObjectName("text_note")
        self.add_notes = QtWidgets.QPushButton(self.groupBox_5)
        self.add_notes.setGeometry(QtCore.QRect(1525, 50, 61, 61))
        self.add_notes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_notes.setToolTip("")
        self.add_notes.setToolTipDuration(0)
        self.add_notes.setText("")
        self.add_notes.setIcon(icon5)
        self.add_notes.setIconSize(QtCore.QSize(61, 61))
        self.add_notes.setCheckable(False)
        self.add_notes.setChecked(False)
        self.add_notes.setDefault(False)
        self.add_notes.setObjectName("add_notes")
        self.choice_color_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.choice_color_btn.setGeometry(QtCore.QRect(1444, 81, 35, 35))
        self.choice_color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choice_color_btn.setStyleSheet("")
        self.choice_color_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Дизайн/icons/выбор цвета.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.choice_color_btn.setIcon(icon12)
        self.choice_color_btn.setIconSize(QtCore.QSize(35, 35))
        self.choice_color_btn.setObjectName("choice_color_btn")
        self.choice_color = QtWidgets.QGroupBox(self.groupBox_5)
        self.choice_color.setGeometry(QtCore.QRect(1450, 140, 60, 201))
        self.choice_color.setTitle("")
        self.choice_color.setObjectName("choice_color")
        self.red = QtWidgets.QRadioButton(self.choice_color)
        self.red.setGeometry(QtCore.QRect(2, 10, 55, 35))
        self.red.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Дизайн/icons/выбор красного цвета.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.red.setIcon(icon13)
        self.red.setIconSize(QtCore.QSize(35, 35))
        self.red.setCheckable(True)
        self.red.setAutoExclusive(True)
        self.red.setObjectName("red")
        self.blue = QtWidgets.QRadioButton(self.choice_color)
        self.blue.setGeometry(QtCore.QRect(2, 55, 55, 35))
        self.blue.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Дизайн/icons/выбор синего цвета.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.blue.setIcon(icon14)
        self.blue.setIconSize(QtCore.QSize(35, 35))
        self.blue.setCheckable(True)
        self.blue.setAutoExclusive(True)
        self.blue.setObjectName("blue")
        self.pink = QtWidgets.QRadioButton(self.choice_color)
        self.pink.setGeometry(QtCore.QRect(2, 100, 55, 35))
        self.pink.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Дизайн/icons/выбор розового цвета.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pink.setIcon(icon15)
        self.pink.setIconSize(QtCore.QSize(35, 35))
        self.pink.setCheckable(True)
        self.pink.setAutoExclusive(True)
        self.pink.setObjectName("pink")
        self.yourself_color = QtWidgets.QPushButton(self.choice_color)
        self.yourself_color.setGeometry(QtCore.QRect(8, 145, 45, 45))
        self.yourself_color.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yourself_color.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Дизайн/icons/выбор цвета самому.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.yourself_color.setIcon(icon16)
        self.yourself_color.setIconSize(QtCore.QSize(45, 45))
        self.yourself_color.setObjectName("yourself_color")
        self.change_note = QtWidgets.QPushButton(self.groupBox_5)
        self.change_note.setGeometry(QtCore.QRect(180, 510, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.change_note.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.change_note.setFont(font)
        self.change_note.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_note.setToolTip("")
        self.change_note.setObjectName("change_note")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(280, -10, 0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background-color: rgb(28, 30, 35);\n"
"")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.itogo_5 = QtWidgets.QLabel(self.groupBox_6)
        self.itogo_5.setGeometry(QtCore.QRect(1289, 960, 71, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.itogo_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.itogo_5.setFont(font)
        self.itogo_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.itogo_5.setStyleSheet("border-bottom-color: rgb(0, 255, 0);")
        self.itogo_5.setLineWidth(10)
        self.itogo_5.setObjectName("itogo_5")
        self.itogo_price_all = QtWidgets.QLabel(self.groupBox_6)
        self.itogo_price_all.setGeometry(QtCore.QRect(1380, 960, 151, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(10, 122, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 122, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 30, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.itogo_price_all.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.itogo_price_all.setFont(font)
        self.itogo_price_all.setObjectName("itogo_price_all")
        self.itogo_icon_all = QtWidgets.QLabel(self.groupBox_6)
        self.itogo_icon_all.setGeometry(QtCore.QRect(1510, 950, 31, 16))
        self.itogo_icon_all.setText("")
        self.itogo_icon_all.setObjectName("itogo_icon_all")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inp_time_todo.setPlaceholderText(_translate("MainWindow", "23:59"))
        self.text_todo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Сделать домашнее задание по тригонометрии</span></p></body></html>"))
        self.time_todo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0785fa;\">19:30</span></p></body></html>"))
        self.text_buy.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Книга Стивен Хоккинг &quot;Краткая история времени&quot;</span></p></body></html>"))
        self.price_text.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0785fa;\">600</span></p></body></html>"))
        self.count.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0785fa;\">600</span></p></body></html>"))
        self.price_for_one.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0785fa;\">600</span></p></body></html>"))
        self.already_buy.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Куплено:</span></p></body></html>"))
        self.already_pay.setText(_translate("MainWindow", "0"))
        self.itogo_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Итого:</span></p></body></html>"))
        self.itogo_price.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Покупки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Выполненные дела"))
        self.change_note.setText(_translate("MainWindow", "Редактировать"))
        self.itogo_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Итого:</span></p></body></html>"))
        self.itogo_price_all.setText(_translate("MainWindow", "0"))

from pyqtgraph import PlotWidget
